### ISSUE TITLE
Some undocumented members don't appear in the documentation

### ISSUE THREAD

**Issue by devnoname120** [vitasdk/vita-headers#111]
Example:

https://docs.vitasdk.org/group__SceSystemParamUser.html

The `SCE_SYSTEM_PARAM_LANG` enumeration only has a 3 members in the documentation when it should have a lot more.

**Comment by scribam** [comment]
@devnoname120 I think it is fixed for the `SCE_SYSTEM_PARAM_LANG` enumeration: https://docs.vitasdk.org/group__SceSystemParamUser.html#gaae33ce498fb58ec8fb018e03635e33cd

**Comment by devnoname120** [comment]
It's "fixed" since someone added comments to the enumeration. The underlying issue is still here as can be seen in this file:
- https://docs.vitasdk.org/group__SceGpioKernel.html
- https://github.com/vitasdk/vita-headers/blob/9c3022090656961d148207dd1774a2702d4bd4fe/include/psp2kern/lowio/gpio.h

**Comment by devnoname120** [comment]
Note that while functions that are not documented still appear in their respective module, they don't appear in search which is a big issue.

**Comment by devnoname120** [comment]
Fixed by https://github.com/vitasdk/vita-headers/pull/421
